import { basename } from 'node:path';
import type { MorningReport, MorningBranchEntry } from './render-morning.js';
import { PLAIN, outcomeLine, describeTest } from './render-morning.js';

// Render a MorningReport as a durable, shareable Markdown receipt. Same data model
// as the terminal renderer (render-morning.ts) — single source of truth. Reuses
// PLAIN (no ANSI) and outcomeLine (the honesty switch lives in ONE place: only a
// real 'weekly-drained' reason may claim the week was drained).
export function renderReceiptMarkdown(report: MorningReport): string {
  const lines: string[] = [];
  const project = basename(report.project_path || '') || 'project';

  lines.push(`# glean — ${project} — ${formatDate(report.started_at, report.ended_at)}`);
  lines.push('');
  lines.push(`**${outcomeLine(report.exit_reason, PLAIN)}**`);
  if (report.bursts !== undefined) {
    lines.push('');
    lines.push(
      report.bursts === 0
        ? '_Coverage: 0 bursts — nothing ran this window._'
        : `_Coverage: woke for ${report.bursts} ${report.bursts === 1 ? 'burst' : 'bursts'} this window._`,
    );
  }
  lines.push('');
  lines.push(totalsLine(report));
  lines.push('');

  if (report.branches.length > 0) {
    lines.push('## Draft branches');
    lines.push('');
    for (const b of report.branches) renderBranch(b, report.main_repo, lines);
  }

  if (report.files.length > 0) {
    lines.push('## Dossiers');
    lines.push('');
    for (const f of report.files) {
      const ok = f.status === 'ok' || f.status === 'ok-fallback';
      lines.push(`- ${ok ? '✓' : '✗'} **${f.title}** — \`${normalizePath(f.output)}\``);
    }
    lines.push('');
  }

  lines.push('---');
  const hits = report.rate_limit_hits;
  lines.push(`_${hits} rate-limit ${hits === 1 ? 'hit' : 'hits'} · generated by \`glean morning\`._`);
  return lines.join('\n');
}

function totalsLine(r: MorningReport): string {
  const realBranches = r.branches.filter((b) => b.prep_branch);
  const ins = realBranches.reduce((s, b) => s + b.insertions, 0);
  const del = realBranches.reduce((s, b) => s + b.deletions, 0);
  const parts = [
    `${realBranches.length} draft ${realBranches.length === 1 ? 'branch' : 'branches'}`,
    `${r.files.length} ${r.files.length === 1 ? 'dossier' : 'dossiers'}`,
    `+${ins} / -${del} across the window`,
  ];
  if (r.drained_minutes !== undefined) parts.push(`~${r.drained_minutes} min`);
  return `**Totals:** ${parts.join(' · ')}`;
}

function renderBranch(b: MorningBranchEntry, mainRepo: string, lines: string[]): void {
  // A draft-impl that produced no branch (provisioning/commit failed).
  if (!b.prep_branch) {
    lines.push(`### draft attempted — ${b.title}`);
    lines.push('_attempted — nothing landed (review logs)._');
    lines.push('');
    return;
  }
  lines.push(`### \`${b.prep_branch}\` — ${b.title}`);
  const trivial = b.files === 0 || b.insertions + b.deletions === 0;
  lines.push(
    trivial
      ? '_draft produced no changes (review)._'
      : `\`+${b.insertions} / -${b.deletions}\` across ${b.files} ${b.files === 1 ? 'file' : 'files'} · tests: ${describeTest(b.test_status)}`,
  );
  lines.push('');
  lines.push(`- **Review:** \`cd ${b.worktree}\``);
  lines.push(`- **Discard:** \`git -C ${mainRepo} worktree remove --force ${b.worktree} && git -C ${mainRepo} branch -D ${b.prep_branch}\``);
  lines.push('- Your `main` was never touched — nothing pushed, nothing merged.');
  lines.push('');
}

function formatDate(start: number, end: number | null): string {
  const d = new Date(end ?? start);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function normalizePath(p: string): string {
  const m = p.match(/^(.*?[/\\])glean[/\\]dossiers[/\\](.*)$/);
  if (m) return `~/glean/dossiers/${m[2].replace(/\\/g, '/')}`;
  return p.replace(/\\/g, '/');
}
