/**
 * schedule.ts — Windows Task Scheduler integration for `glean schedule`.
 *
 * DESIGN:
 *   - buildRegisterScript() is a pure function that returns a PowerShell
 *     script string.  It can be unit-tested without touching the OS.
 *   - enableSchedule() runs that script via execFileSync.
 *   - disableSchedule() unregisters the task.
 *   - scheduleStatus() returns a human-readable summary.
 *
 * All three OS-touching functions guard against non-Windows platforms.
 */

import { execFileSync } from 'node:child_process';

export const TASK_NAME = 'Glean\\Drain';

// Defaults mirrored in the spec.
export const DEFAULT_TIME           = '18:00';
export const DEFAULT_REPEAT_MINUTES = 60;
export const DEFAULT_DURATION_HOURS = 60;

export type TriggerDay = 'Thursday' | 'Friday';

// Timezones whose work week runs Sunday–Thursday, so the LAST work day is Thursday.
// Most former Sun–Thu countries have moved to Fri–Sat or Sat–Sun weekends; Israel
// is the main remaining case. Expand this set only if a user reports a missing zone.
const SUN_THU_ZONES = new Set<string>(['Asia/Jerusalem']);

// The default weekly drain-trigger day = the end of the LAST work day, when the
// week's Claude capacity is most idle. Sun–Thu work weeks (Israel) → Thursday;
// everyone else (including 'UTC' / unknown) → Friday. `tz` is a call-time default
// param so this is unit-testable by passing a fixed zone — no Intl mocking and no
// dependence on the machine's real locale.
export function defaultTriggerDay(
  tz: string = Intl.DateTimeFormat().resolvedOptions().timeZone,
): TriggerDay {
  return SUN_THU_ZONES.has(tz) ? 'Thursday' : 'Friday';
}

export type BuildRegisterScriptOpts = {
  /** Absolute path to the `node` executable (process.execPath at call time). */
  nodePath: string;
  /** Absolute path to `bin/glean.js` in the install. */
  cliEntry: string;
  /** Absolute path to the project repo this drain run targets. */
  projectPath: string;
  /** Day of week for the weekly trigger, e.g. 'Thursday'. */
  day?: string;
  /** Local 24-h HH:MM start time for the weekly trigger, e.g. '18:00'. */
  time?: string;
  /** Repetition interval in minutes inside the trigger window. */
  repeatMinutes?: number;
  /** Duration in hours that the repetition window stays active. */
  durationHours?: number;
};

/**
 * Returns a complete PowerShell script that registers the `Glean\Drain`
 * scheduled task.  The script is idempotent: if the task already exists
 * it is replaced (Register-ScheduledTask -Force).
 *
 * This is a pure function — it produces a string and touches nothing.
 */
export function buildRegisterScript(opts: BuildRegisterScriptOpts): string {
  const day            = opts.day            ?? defaultTriggerDay();
  const time           = opts.time           ?? DEFAULT_TIME;
  const repeatMinutes  = opts.repeatMinutes  ?? DEFAULT_REPEAT_MINUTES;
  const durationHours  = opts.durationHours  ?? DEFAULT_DURATION_HOURS;

  // Escape any embedded double-quotes in paths (PowerShell string safety).
  const safeNode    = opts.nodePath.replace(/"/g, '`"');
  const safeCli     = opts.cliEntry.replace(/"/g, '`"');
  const safeProject = opts.projectPath.replace(/"/g, '`"');

  // Convert durationHours to a TimeSpan string understood by New-ScheduledTaskTrigger.
  // PT60H → ISO 8601 period, or we can use the direct cmdlet param format.
  // PowerShell New-ScheduledTaskTrigger accepts -RandomDelay as a TimeSpan string.
  // For RepetitionInterval and RepetitionDuration we pass TimeSpan strings.
  const repeatInterval = `([TimeSpan]::FromMinutes(${repeatMinutes}))`;
  const repeatDuration = `([TimeSpan]::FromHours(${durationHours}))`;

  return `
# Glean Drain — register Windows Scheduled Task
# Generated by glean schedule enable

$ErrorActionPreference = 'Stop'

$action = New-ScheduledTaskAction \`
  -Execute "${safeNode}" \`
  -Argument "\`"${safeCli}\`" run --drain --project \`"${safeProject}\`""

$trigger = New-ScheduledTaskTrigger \`
  -Weekly \`
  -DaysOfWeek ${day} \`
  -At "${time}"

# Repetition sub-properties (.Repetition.Interval/.Duration) are READ-ONLY on a
# weekly trigger in PowerShell 7 — assigning them throws. The reliable pattern is
# to build the repetition from a throwaway -Once trigger and assign the whole
# .Repetition object. Verified live against PowerShell 7 (Interval=PT1H etc.).
$trigger.Repetition = (New-ScheduledTaskTrigger -Once -At "${time}" \`
  -RepetitionInterval ${repeatInterval} \`
  -RepetitionDuration ${repeatDuration}).Repetition

$settings = New-ScheduledTaskSettingsSet \`
  -StartWhenAvailable \`
  -AllowStartIfOnBatteries \`
  -DontStopIfGoingOnBatteries \`
  -MultipleInstances IgnoreNew \`
  -WakeToRun:$false \`
  -ExecutionTimeLimit ([TimeSpan]::Zero)

$principal = New-ScheduledTaskPrincipal \`
  -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) \`
  -LogonType Interactive \`
  -RunLevel Limited

# Register-ScheduledTask -Force auto-creates the \\Glean subfolder; no COM needed.
Register-ScheduledTask \`
  -TaskName "${TASK_NAME}" \`
  -Action $action \`
  -Trigger $trigger \`
  -Settings $settings \`
  -Principal $principal \`
  -Force | Out-Null

Write-Host "Glean\\Drain task registered. Next run: ${day} at ${time} (repeats every ${repeatMinutes}min for ${durationHours}h)."
`.trimStart();
}

function assertWindows(): void {
  if (process.platform !== 'win32') {
    throw new Error('glean schedule is Windows-only in v0.8.0');
  }
}

export type EnableScheduleOpts = BuildRegisterScriptOpts;

/**
 * Registers (or replaces) the Glean\Drain scheduled task.
 * Throws on non-Windows or if PowerShell exits non-zero.
 */
export function enableSchedule(opts: EnableScheduleOpts): void {
  assertWindows();
  const script = buildRegisterScript(opts);
  execFileSync('powershell', ['-NonInteractive', '-NoProfile', '-Command', script], {
    stdio: ['ignore', 'inherit', 'inherit'],
    windowsHide: true,
  });
}

/**
 * Unregisters the Glean\Drain scheduled task.
 * A no-op (exit 0) if the task does not exist.
 */
export function disableSchedule(): void {
  assertWindows();
  const cmd = `Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false -ErrorAction SilentlyContinue`;
  execFileSync('powershell', ['-NonInteractive', '-NoProfile', '-Command', cmd], {
    stdio: ['ignore', 'inherit', 'inherit'],
    windowsHide: true,
  });
  console.log(`Glean\\Drain task removed (or was not present).`);
}

export type ScheduleStatusResult =
  | { found: false }
  | { found: true; state: string; lastRun: string; nextRun: string; taskName: string };

/**
 * Returns the current status of the Glean\Drain task.
 * Returns { found: false } when the task does not exist.
 */
export function scheduleStatus(): ScheduleStatusResult {
  assertWindows();

  const cmd = `
$ErrorActionPreference = 'SilentlyContinue'
$t = Get-ScheduledTask -TaskName '${TASK_NAME}' 2>$null
if (-not $t) { Write-Output 'NOT_FOUND'; exit 0 }
$info = Get-ScheduledTaskInfo -TaskName '${TASK_NAME}' 2>$null
$state = $t.State
$lastRun = if ($info.LastRunTime) { $info.LastRunTime.ToString('o') } else { 'never' }
$nextRun = if ($info.NextRunTime) { $info.NextRunTime.ToString('o') } else { 'unknown' }
Write-Output "FOUND|$state|$lastRun|$nextRun"
`.trim();

  let raw: string;
  try {
    raw = execFileSync('powershell', ['-NonInteractive', '-NoProfile', '-Command', cmd], {
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
      encoding: 'utf8',
    }).trim();
  } catch {
    return { found: false };
  }

  if (!raw || raw === 'NOT_FOUND') return { found: false };

  const parts = raw.split('|');
  if (parts.length < 4) return { found: false };
  return {
    found: true,
    taskName: TASK_NAME,
    state: parts[1],
    lastRun: parts[2],
    nextRun: parts[3],
  };
}
