/**
 * serve-install.ts — auto-start for the `glean serve` dashboard.
 *
 * Plain `glean serve` is terminal-bound: the dashboard dies with the terminal,
 * which in practice means it is down whenever you actually want to glance at
 * it. `glean serve install` registers the dashboard to start at user logon
 * and restart on failure:
 *
 *   - win32: a second scheduled task `Glean\Serve` (logon trigger, hidden,
 *     current user only) — exact mirror of schedule.ts's `Glean\Drain`
 *     pattern: pure build*() string builders + thin exec wrappers.
 *   - linux: a systemd USER service `glean-serve.service`
 *     (`Restart=on-failure`), enabled via `systemctl --user enable --now`.
 *   - darwin: not yet — install/uninstall/status throw.
 *
 * Same testing contract as schedule.ts: builders/parsers are pure and run on
 * any OS; exec wrappers are platform-gated and never registered in tests.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { systemdUserAvailable, systemdUserDir, psDoubleQuoteEscape } from './schedule.js';

export const SERVE_TASK_NAME = 'Glean\\Serve';
// v0.8.3 lesson (see schedule.ts): Register-ScheduledTask accepts the combined
// 'Glean\Serve' form, but the read/start/delete cmdlets only match the folder
// and leaf SPLIT into -TaskPath + -TaskName.
export const SERVE_TASK_PATH = '\\Glean\\';
export const SERVE_TASK_LEAF = 'Serve';

export const SERVE_SYSTEMD_SERVICE = 'glean-serve.service';

export const DEFAULT_SERVE_PORT = 4317;

export type ServeInstallOpts = {
  /** Absolute path to the `node` executable (process.execPath at call time). */
  nodePath: string;
  /** Absolute path to `bin/glean.js` in the install. */
  cliEntry: string;
  /** Dashboard port (default 4317). */
  port?: number;
};

/**
 * Pure — the PowerShell that registers the `Glean\Serve` logon task.
 * Idempotent (Register-ScheduledTask -Force replaces an existing task).
 *
 * Notes mirrored from buildRegisterScript plus serve-specific choices:
 *   - The action runs `conhost.exe --headless node <cli> serve --port N`:
 *     node is a console app, and an interactive logon task would otherwise
 *     park a visible console window on the desktop at every logon.
 *   - RestartCount/RestartInterval make Task Scheduler relaunch the dashboard
 *     if it dies (the systemd analog is Restart=on-failure).
 *   - ExecutionTimeLimit Zero: serve runs until logoff/stop, not for a window.
 *   - The script never starts the task: see buildServeStartCommand(), which
 *     the install wrapper can skip when a dashboard is already live.
 */
export function buildServeRegisterScript(opts: ServeInstallOpts): string {
  const port = opts.port ?? DEFAULT_SERVE_PORT;

  // Escape PowerShell interpolation metachars in paths (`"`, backtick, `$`) so a
  // `$(...)` subexpression or backtick escape in a path cannot execute (F3).
  const safeNode = psDoubleQuoteEscape(opts.nodePath);
  const safeCli = psDoubleQuoteEscape(opts.cliEntry);

  return `
# Glean Serve — register the dashboard auto-start task (logon trigger)
# Generated by glean serve install

$ErrorActionPreference = 'Stop'

# conhost --headless hosts the console app with no window; node directly would
# pin a visible console to the desktop for the whole session.
$action = New-ScheduledTaskAction \`
  -Execute "$env:SystemRoot\\System32\\conhost.exe" \`
  -Argument "--headless \`"${safeNode}\`" \`"${safeCli}\`" serve --port ${port}"

$trigger = New-ScheduledTaskTrigger \`
  -AtLogOn \`
  -User ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name)

$settings = New-ScheduledTaskSettingsSet \`
  -AllowStartIfOnBatteries \`
  -DontStopIfGoingOnBatteries \`
  -MultipleInstances IgnoreNew \`
  -RestartCount 3 \`
  -RestartInterval (New-TimeSpan -Minutes 1) \`
  -ExecutionTimeLimit ([TimeSpan]::Zero)

$principal = New-ScheduledTaskPrincipal \`
  -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) \`
  -LogonType Interactive \`
  -RunLevel Limited

# Register-ScheduledTask -Force auto-creates the \\Glean subfolder; no COM needed.
Register-ScheduledTask \`
  -TaskName "${SERVE_TASK_NAME}" \`
  -Action $action \`
  -Trigger $trigger \`
  -Settings $settings \`
  -Principal $principal \`
  -Force | Out-Null

Write-Host "Glean\\Serve task registered: dashboard starts at logon on http://127.0.0.1:${port}/ (restarts on failure)."
`.trimStart();
}

/** Pure — starts the registered task now (split path + leaf form, see above). */
export function buildServeStartCommand(): string {
  return `Start-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}'`;
}

/**
 * Pure — stops the running dashboard, then unregisters the task.
 * A no-op (exit 0) when the task does not exist.
 */
export function buildServeUnregisterScript(): string {
  return [
    // Stop first: unregistering alone leaves the spawned node process running.
    `Stop-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' -ErrorAction SilentlyContinue`,
    `Unregister-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' -Confirm:$false -ErrorAction SilentlyContinue`,
  ].join('\n');
}

/**
 * Pure — the PowerShell that reads Glean\Serve status. Emits:
 *   NOT_FOUND                                  when the task is absent
 *   FOUND|<state>|<lastRun>|<action arguments> when present
 * The action arguments are echoed so the installed port can be recovered
 * (parseServeStatusOutput). `$actionArgs`, not `$args` — that one is a
 * PowerShell automatic variable.
 */
export function buildServeStatusScript(): string {
  return `
$ErrorActionPreference = 'SilentlyContinue'
$t = Get-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' 2>$null
if (-not $t) { Write-Output 'NOT_FOUND'; exit 0 }
$info = Get-ScheduledTaskInfo -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' 2>$null
$state = $t.State
$lastRun = if ($info.LastRunTime) { $info.LastRunTime.ToString('o') } else { 'never' }
$actionArgs = ($t.Actions | Select-Object -First 1).Arguments
Write-Output "FOUND|$state|$lastRun|$actionArgs"
`.trim();
}

export type ServeTaskStatus =
  | { found: false }
  | { found: true; state: string; lastRun: string; port: number | null };

/**
 * Pure — parse buildServeStatusScript()'s output line. The trailing field is
 * the task action's raw arguments; the installed port is recovered from the
 * `serve --port N` inside it (null when absent/unparseable).
 */
export function parseServeStatusOutput(raw: string): ServeTaskStatus {
  const line = raw.trim();
  if (!line.startsWith('FOUND|')) return { found: false };
  const parts = line.split('|');
  if (parts.length < 4) return { found: false };
  const actionArgs = parts.slice(3).join('|');
  const portMatch = actionArgs.match(/serve\s+--port\s+(\d+)/);
  return {
    found: true,
    state: parts[1],
    lastRun: parts[2],
    port: portMatch ? Number(portMatch[1]) : null,
  };
}

// ===========================================================================
// Linux — systemd user SERVICE (not a timer: serve is a long-running process)
// ===========================================================================

/** The serve command shared by the unit builder (quoted for spaced paths). */
function serveCommand(opts: ServeInstallOpts): string {
  return `"${opts.nodePath}" "${opts.cliEntry}" serve --port ${opts.port ?? DEFAULT_SERVE_PORT}`;
}

/**
 * Pure — glean-serve.service: a long-running user service for the dashboard.
 * `Restart=on-failure` is the systemd analog of the Windows task's
 * RestartCount/RestartInterval; WantedBy=default.target starts it at login.
 */
export function buildServeServiceUnit(opts: ServeInstallOpts): string {
  return `[Unit]
Description=Glean dashboard (glean serve — local management surface on 127.0.0.1)

[Service]
ExecStart=${serveCommand(opts)}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
}

/** Pure — recover the installed port from a glean-serve.service unit file. */
export function parseServePortFromUnit(unitText: string): number | null {
  const m = unitText.match(/serve\s+--port\s+(\d+)/);
  return m ? Number(m[1]) : null;
}

// ===========================================================================
// Liveness — is a glean dashboard actually answering on the port?
// ===========================================================================

/**
 * True when a *glean dashboard* answers GET /api/overview on 127.0.0.1:<port>
 * within `timeoutMs`. A foreign process that happens to own the port (or a
 * server that hangs) is false — the overview JSON's `drain` key is the
 * fingerprint that this is really us.
 *
 * The default timeout is a hang-guard, not an expected wait: a dead port
 * fails fast (ECONNREFUSED), so the full timeout is only ever spent when the
 * port-owner accepts but never answers. It is deliberately generous because
 * a CROSS-PROCESS loopback connect on Windows can take ~7s (measured on the
 * dev box: in-process connects are instant, process→process connects hit a
 * SYN-retransmit pattern — likely WFP/AV filtering). A tighter default made
 * the CLI misreport a live dashboard as a foreign process.
 */
export async function serveAlive(port: number, timeoutMs = 10_000): Promise<boolean> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(`http://127.0.0.1:${port}/api/overview`, { signal: ctrl.signal });
    if (!res.ok) return false;
    const body: unknown = await res.json();
    return typeof body === 'object' && body !== null && 'drain' in body;
  } catch {
    return false;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Pure — the polite singleton message when `glean serve` finds its port
 * already owned by a live glean dashboard. `installed` is the Glean\Serve
 * registration answer (null when it could not be determined).
 */
export function formatAlreadyRunning(port: number, installed: boolean | null): string {
  const url = `http://127.0.0.1:${port}/`;
  const suffix =
    installed === true
      ? "installed: yes — the auto-start task owns it ('glean serve uninstall' removes it)"
      : installed === false
        ? "installed: no — another foreground 'glean serve' owns this port"
        : 'installed: unknown';
  return `glean dashboard already running at ${url} (${suffix})`;
}

// ===========================================================================
// Exec wrappers — thin, platform-gated (never run in tests beyond read-only)
// ===========================================================================

function assertServeInstallSupported(): void {
  if (process.platform !== 'win32' && process.platform !== 'linux') {
    throw new Error(
      'glean serve install supports Windows (Task Scheduler logon task) and Linux (systemd user service); macOS launchd is future work',
    );
  }
}

function powershell(command: string, capture: false): void;
function powershell(command: string, capture: true): string;
function powershell(command: string, capture: boolean): string | void {
  const out = execFileSync('powershell', ['-NonInteractive', '-NoProfile', '-Command', command], {
    stdio: ['ignore', capture ? 'pipe' : 'inherit', 'inherit'],
    windowsHide: true,
    encoding: 'utf8',
  });
  if (capture) return out;
}

function systemctlUser(args: string[]): void {
  execFileSync('systemctl', ['--user', ...args], { stdio: ['ignore', 'inherit', 'inherit'] });
}

/**
 * Registers (or replaces) the dashboard auto-start at user logon, and starts
 * it now unless `startNow` is false (the CLI passes false when a dashboard is
 * already live on the port, so Task Scheduler doesn't burn its restart budget
 * on EADDRINUSE exits).
 */
export function installServe(opts: ServeInstallOpts, startNow = true): void {
  assertServeInstallSupported();
  const port = opts.port ?? DEFAULT_SERVE_PORT;
  if (process.platform === 'linux') {
    installServeLinux(opts, startNow);
    return;
  }
  powershell(buildServeRegisterScript(opts), false);
  if (startNow) {
    powershell(buildServeStartCommand(), false);
    console.log(`Glean\\Serve started: http://127.0.0.1:${port}/`);
  }
}

function installServeLinux(opts: ServeInstallOpts, startNow: boolean): void {
  if (!systemdUserAvailable()) {
    throw new Error(
      'systemd --user is unavailable on this box — glean serve install needs it to supervise the dashboard; run `glean serve` manually instead',
    );
  }
  const port = opts.port ?? DEFAULT_SERVE_PORT;
  const dir = systemdUserDir();
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, SERVE_SYSTEMD_SERVICE), buildServeServiceUnit(opts));
  systemctlUser(['daemon-reload']);
  systemctlUser(startNow ? ['enable', '--now', SERVE_SYSTEMD_SERVICE] : ['enable', SERVE_SYSTEMD_SERVICE]);
  console.log(
    `${SERVE_SYSTEMD_SERVICE} enabled: dashboard on http://127.0.0.1:${port}/ at login (Restart=on-failure).`,
  );
}

/**
 * Removes the auto-start registration AND stops the running dashboard.
 * A no-op when nothing is installed.
 */
export function uninstallServe(): void {
  assertServeInstallSupported();
  if (process.platform === 'linux') {
    uninstallServeLinux();
    return;
  }
  powershell(buildServeUnregisterScript(), false);
  console.log('Glean\\Serve task removed (or was not present); the dashboard, if running under it, was stopped.');
}

function uninstallServeLinux(): void {
  if (systemdUserAvailable()) {
    try {
      systemctlUser(['disable', '--now', SERVE_SYSTEMD_SERVICE]);
    } catch {
      /* not enabled — fine */
    }
  }
  const unitPath = join(systemdUserDir(), SERVE_SYSTEMD_SERVICE);
  try {
    if (existsSync(unitPath)) unlinkSync(unitPath);
  } catch {
    /* best effort */
  }
  if (systemdUserAvailable()) {
    try {
      systemctlUser(['daemon-reload']);
    } catch {
      /* best effort */
    }
  }
  console.log(`${SERVE_SYSTEMD_SERVICE} removed (or was not present).`);
}

/**
 * Reads the auto-start registration state (read-only — safe everywhere).
 * win32: Glean\Serve task via the status script. linux: the unit file +
 * `systemctl --user is-active`. Throws on unsupported platforms.
 */
export function serveTaskStatus(): ServeTaskStatus {
  assertServeInstallSupported();
  if (process.platform === 'linux') return serveTaskStatusLinux();
  let raw: string;
  try {
    raw = powershell(buildServeStatusScript(), true).trim();
  } catch {
    return { found: false };
  }
  return parseServeStatusOutput(raw);
}

function serveTaskStatusLinux(): ServeTaskStatus {
  const unitPath = join(systemdUserDir(), SERVE_SYSTEMD_SERVICE);
  if (!existsSync(unitPath)) return { found: false };
  let port: number | null = null;
  try {
    port = parseServePortFromUnit(readFileSync(unitPath, 'utf8'));
  } catch {
    /* unreadable unit — report found with unknown port */
  }
  let state = 'inactive';
  try {
    state = execFileSync('systemctl', ['--user', 'is-active', SERVE_SYSTEMD_SERVICE], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    state = 'inactive';
  }
  return { found: true, state, lastRun: 'unknown', port };
}

// ===========================================================================
// `glean serve status` — composed report + pure renderer
// ===========================================================================

export type ServeStatusReport = {
  /** Whether auto-start install is supported on this platform at all. */
  supported: boolean;
  /** Platform-appropriate registration label, e.g. 'Glean\\Serve task'. */
  label: string;
  registered: boolean;
  state: string | null;
  lastRun: string | null;
  /** Port parsed back from the registration (task args / unit file). */
  installedPort: number | null;
  /** Port liveness was probed on (explicit flag > installed > default). */
  probePort: number;
  running: boolean;
};

export function serveInstallLabel(): string {
  return process.platform === 'win32' ? 'Glean\\Serve task' : SERVE_SYSTEMD_SERVICE;
}

/** Registration state + dashboard liveness in one read-only report. */
export async function serveStatusReport(portFlag?: number): Promise<ServeStatusReport> {
  let supported = true;
  let status: ServeTaskStatus = { found: false };
  try {
    status = serveTaskStatus();
  } catch {
    supported = false;
  }
  const installedPort = status.found ? status.port : null;
  const probePort = portFlag ?? installedPort ?? DEFAULT_SERVE_PORT;
  const running = await serveAlive(probePort);
  return {
    supported,
    label: serveInstallLabel(),
    registered: status.found,
    state: status.found ? status.state : null,
    lastRun: status.found ? status.lastRun : null,
    installedPort,
    probePort,
    running,
  };
}

/** Pure — the `glean serve status` text. */
export function renderServeStatus(r: ServeStatusReport): string {
  const lines: string[] = [];
  if (!r.supported) {
    lines.push(`${r.label}: auto-start install not supported on this platform (Windows + Linux only)`);
  } else if (!r.registered) {
    lines.push(`${r.label}: not registered — \`glean serve install\` keeps the dashboard always on`);
  } else {
    lines.push(`${r.label}: registered (${r.state})`);
    lines.push(`  last run: ${r.lastRun}`);
    lines.push(`  port: ${r.installedPort ?? 'unknown'}`);
  }
  lines.push(
    r.running
      ? `dashboard: responding at http://127.0.0.1:${r.probePort}/`
      : `dashboard: not responding on port ${r.probePort}`,
  );
  return lines.join('\n');
}
