/**
 * serve-install.ts — auto-start for the `glean serve` dashboard.
 *
 * Plain `glean serve` is terminal-bound: the dashboard dies with the terminal,
 * which in practice means it is down whenever you actually want to glance at
 * it. `glean serve install` registers the dashboard to start at user logon
 * and restart on failure:
 *
 *   - win32: a second scheduled task `Glean\Serve` (logon trigger, hidden,
 *     current user only) — exact mirror of schedule.ts's `Glean\Drain`
 *     pattern: pure build*() string builders + thin exec wrappers.
 *   - linux: a systemd USER service `glean-serve.service`
 *     (`Restart=on-failure`), enabled via `systemctl --user enable --now`.
 *   - darwin: not yet — install/uninstall/status throw.
 *
 * Same testing contract as schedule.ts: builders/parsers are pure and run on
 * any OS; exec wrappers are platform-gated and never registered in tests.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { systemdUserAvailable, systemdUserDir } from './schedule.js';

export const SERVE_TASK_NAME = 'Glean\\Serve';
// v0.8.3 lesson (see schedule.ts): Register-ScheduledTask accepts the combined
// 'Glean\Serve' form, but the read/start/delete cmdlets only match the folder
// and leaf SPLIT into -TaskPath + -TaskName.
export const SERVE_TASK_PATH = '\\Glean\\';
export const SERVE_TASK_LEAF = 'Serve';

export const SERVE_SYSTEMD_SERVICE = 'glean-serve.service';

export const DEFAULT_SERVE_PORT = 4317;

export type ServeInstallOpts = {
  /** Absolute path to the `node` executable (process.execPath at call time). */
  nodePath: string;
  /** Absolute path to `bin/glean.js` in the install. */
  cliEntry: string;
  /** Dashboard port (default 4317). */
  port?: number;
};

/**
 * Pure — the PowerShell that registers the `Glean\Serve` logon task.
 * Idempotent (Register-ScheduledTask -Force replaces an existing task).
 *
 * Notes mirrored from buildRegisterScript plus serve-specific choices:
 *   - The action runs `conhost.exe --headless node <cli> serve --port N`:
 *     node is a console app, and an interactive logon task would otherwise
 *     park a visible console window on the desktop at every logon.
 *   - RestartCount/RestartInterval make Task Scheduler relaunch the dashboard
 *     if it dies (the systemd analog is Restart=on-failure).
 *   - ExecutionTimeLimit Zero: serve runs until logoff/stop, not for a window.
 *   - The script never starts the task: see buildServeStartCommand(), which
 *     the install wrapper can skip when a dashboard is already live.
 */
export function buildServeRegisterScript(opts: ServeInstallOpts): string {
  const port = opts.port ?? DEFAULT_SERVE_PORT;

  // Escape any embedded double-quotes in paths (PowerShell string safety).
  const safeNode = opts.nodePath.replace(/"/g, '`"');
  const safeCli = opts.cliEntry.replace(/"/g, '`"');

  return `
# Glean Serve — register the dashboard auto-start task (logon trigger)
# Generated by glean serve install

$ErrorActionPreference = 'Stop'

# conhost --headless hosts the console app with no window; node directly would
# pin a visible console to the desktop for the whole session.
$action = New-ScheduledTaskAction \`
  -Execute "$env:SystemRoot\\System32\\conhost.exe" \`
  -Argument "--headless \`"${safeNode}\`" \`"${safeCli}\`" serve --port ${port}"

$trigger = New-ScheduledTaskTrigger \`
  -AtLogOn \`
  -User ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name)

$settings = New-ScheduledTaskSettingsSet \`
  -AllowStartIfOnBatteries \`
  -DontStopIfGoingOnBatteries \`
  -MultipleInstances IgnoreNew \`
  -RestartCount 3 \`
  -RestartInterval (New-TimeSpan -Minutes 1) \`
  -ExecutionTimeLimit ([TimeSpan]::Zero)

$principal = New-ScheduledTaskPrincipal \`
  -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) \`
  -LogonType Interactive \`
  -RunLevel Limited

# Register-ScheduledTask -Force auto-creates the \\Glean subfolder; no COM needed.
Register-ScheduledTask \`
  -TaskName "${SERVE_TASK_NAME}" \`
  -Action $action \`
  -Trigger $trigger \`
  -Settings $settings \`
  -Principal $principal \`
  -Force | Out-Null

Write-Host "Glean\\Serve task registered: dashboard starts at logon on http://127.0.0.1:${port}/ (restarts on failure)."
`.trimStart();
}

/** Pure — starts the registered task now (split path + leaf form, see above). */
export function buildServeStartCommand(): string {
  return `Start-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}'`;
}

/**
 * Pure — stops the running dashboard, then unregisters the task.
 * A no-op (exit 0) when the task does not exist.
 */
export function buildServeUnregisterScript(): string {
  return [
    // Stop first: unregistering alone leaves the spawned node process running.
    `Stop-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' -ErrorAction SilentlyContinue`,
    `Unregister-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' -Confirm:$false -ErrorAction SilentlyContinue`,
  ].join('\n');
}

/**
 * Pure — the PowerShell that reads Glean\Serve status. Emits:
 *   NOT_FOUND                                  when the task is absent
 *   FOUND|<state>|<lastRun>|<action arguments> when present
 * The action arguments are echoed so the installed port can be recovered
 * (parseServeStatusOutput). `$actionArgs`, not `$args` — that one is a
 * PowerShell automatic variable.
 */
export function buildServeStatusScript(): string {
  return `
$ErrorActionPreference = 'SilentlyContinue'
$t = Get-ScheduledTask -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' 2>$null
if (-not $t) { Write-Output 'NOT_FOUND'; exit 0 }
$info = Get-ScheduledTaskInfo -TaskPath '${SERVE_TASK_PATH}' -TaskName '${SERVE_TASK_LEAF}' 2>$null
$state = $t.State
$lastRun = if ($info.LastRunTime) { $info.LastRunTime.ToString('o') } else { 'never' }
$actionArgs = ($t.Actions | Select-Object -First 1).Arguments
Write-Output "FOUND|$state|$lastRun|$actionArgs"
`.trim();
}
